name: Backend Build, Test, Push & Deploy

on:
  push:
    branches:
      - master
  pull_request:    
    branches:
      - master
  workflow_dispatch:   

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend with Maven
        working-directory: lms-backend
        run: mvn clean package -DskipTests

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies and build frontend
        working-directory: lms-frontend
        run: |
          npm install
          npm run build --prod

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend Docker image
        working-directory: lms-backend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lms-backend:latest .

      - name: Push backend Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/lms-backend:latest

      - name: Build frontend Docker image
        working-directory: lms-frontend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lms-frontend:latest .

      - name: Push frontend Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/lms-frontend:latest

      - name: Deploy to Local Test Environment
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Stopping any existing backend container..."
          docker stop backend || true
          docker rm backend || true
          echo "Starting new backend container..."
          docker run -d --name backend -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
          echo "Running containers:"
          docker ps
